=== heyitsELECTRO/wt_college/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="faculty">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="details" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== heyitsELECTRO/wt_college/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE faculty SYSTEM "index.dtd"> -->
<faculty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">

<details>
    <id>123456</id>
    <password>secure123</password>
</details>

<details>
    <id>123456</id>
    <password>secure123</password>
</details>
<details>
    <id>123456</id>
    <password>secure123</password>
</details>

</faculty>
